### ISSUE TITLE
Installation issue if give exact version number.

### ISSUE THREAD

**Issue by milindc** [QualityUnit/TNEFDecoder#1]
Hello,

I am using this package in one of my project and I found that if I declare the package with exact version number it does not get installed.
Ex. "qualityunit/tnef-decoder": "1.0.0" 

I used this kind of declaration as I can see only one version is available.

Could you please resolve this so that I can start using it.

**Comment by martincivan** [comment]
Hello @milindc 
Sorry for late response, I had accidentally muted notifications.
I am not sure, what the problem is.
I have tried it with exact version "1.0.0", and we use it in our project composer.json like:
`"qualityunit/tnef-decoder": "^1.0",` and it is working just fine. Could you please provide more details what the problem is?
